/*
FUNCTION setDataQueryString RETURNS LOGICAL
  (INPUT cQueryString AS CHARACTER) IN SUPER.
FUNCTION getDataQueryString RETURNS CHARACTER
  () IN SUPER.
FUNCTION setDataQuerySort RETURNS LOGICAL
  (INPUT cQuerySort AS CHARACTER) IN SUPER.
FUNCTION getDataQuerySort RETURNS CHARACTER
  () IN SUPER.  
*/


