  FIELD afecta_stock LIKE Fac_header.afecta_stock VALIDATE ~
  FIELD ano LIKE Fac_header.ano VALIDATE ~
  FIELD anulado LIKE Fac_header.anulado VALIDATE ~
  FIELD aplica_minimos LIKE Fac_header.aplica_minimos VALIDATE ~
  FIELD cai LIKE Fac_header.cai VALIDATE ~
  FIELD cambio LIKE Fac_header.cambio VALIDATE ~
  FIELD cambio_dolar LIKE Fac_header.cambio_dolar VALIDATE ~
  FIELD cant_hojas LIKE Fac_header.cant_hojas VALIDATE ~
  FIELD cdg_administrador LIKE Fac_header.cdg_administrador VALIDATE ~
  FIELD cdg_comprobante LIKE Fac_header.cdg_comprobante VALIDATE ~
  FIELD cdg_condiva LIKE Fac_header.cdg_condiva VALIDATE ~
  FIELD cdg_empresa LIKE Fac_header.cdg_empresa VALIDATE ~
  FIELD cdg_imputacion LIKE Fac_header.cdg_imputacion VALIDATE ~
  FIELD cdg_lista LIKE Fac_header.cdg_lista VALIDATE ~
  FIELD cdg_postal LIKE Fac_header.cdg_postal VALIDATE ~
  FIELD cdg_postal_leg LIKE Fac_header.cdg_postal_leg VALIDATE ~
  FIELD cdg_provincia LIKE Fac_header.cdg_provincia VALIDATE ~
  FIELD cdg_provincia_leg LIKE Fac_header.cdg_provincia_leg VALIDATE ~
  FIELD cdg_zonag LIKE Fac_header.cdg_zonag VALIDATE ~
  FIELD clausula_dolar LIKE Fac_header.clausula_dolar VALIDATE ~
  FIELD codigo_cliente LIKE Fac_header.codigo_cliente VALIDATE ~
  FIELD cta_cte LIKE Fac_header.cta_cte VALIDATE ~
  FIELD cuit LIKE Fac_header.cuit VALIDATE ~
  FIELD direccion LIKE Fac_header.direccion VALIDATE ~
  FIELD direccion_administrador LIKE Fac_header.direccion_administrador VALIDATE ~
  FIELD direccion_leg LIKE Fac_header.direccion_leg VALIDATE ~
  FIELD estado LIKE Fac_header.estado VALIDATE ~
  FIELD fecha LIKE Fac_header.fecha VALIDATE ~
  FIELD fecha_grab LIKE Fac_header.fecha_grab VALIDATE ~
  FIELD fecha_iva LIKE Fac_header.fecha_iva VALIDATE ~
  FIELD fecha_ocm LIKE Fac_header.fecha_ocm VALIDATE ~
  FIELD fecha_precios LIKE Fac_header.fecha_precios VALIDATE ~
  FIELD hora LIKE Fac_header.hora VALIDATE ~
  FIELD hora_grab LIKE Fac_header.hora_grab VALIDATE ~
  FIELD ibrutos_sino LIKE Fac_header.ibrutos_sino VALIDATE ~
  FIELD impreso LIKE Fac_header.impreso VALIDATE ~
  FIELD imp_bruto LIKE Fac_header.imp_bruto VALIDATE ~
  FIELD imp_descuentos LIKE Fac_header.imp_descuentos VALIDATE ~
  FIELD imp_iva LIKE Fac_header.imp_iva VALIDATE ~
  FIELD imp_neto LIKE Fac_header.imp_neto VALIDATE ~
  FIELD imp_total LIKE Fac_header.imp_total VALIDATE ~
  FIELD leyenda LIKE Fac_header.leyenda VALIDATE ~
  FIELD leyenda_cc LIKE Fac_header.leyenda_cc VALIDATE ~
  FIELD localidad LIKE Fac_header.localidad VALIDATE ~
  FIELD localidad_administrador LIKE Fac_header.localidad_administrador VALIDATE ~
  FIELD localidad_leg LIKE Fac_header.localidad_leg VALIDATE ~
  FIELD mes LIKE Fac_header.mes VALIDATE ~
  FIELD modo_abasto LIKE Fac_header.modo_abasto VALIDATE ~
  FIELD modo_remito LIKE Fac_header.modo_remito VALIDATE ~
  FIELD monto_letras LIKE Fac_header.monto_letras VALIDATE ~
  FIELD mostrar_admin LIKE Fac_header.mostrar_admin VALIDATE ~
  FIELD nombre LIKE Fac_header.nombre VALIDATE ~
  FIELD nombre_domicilio LIKE Fac_header.nombre_domicilio VALIDATE ~
  FIELD nombre_leg LIKE Fac_header.nombre_leg VALIDATE ~
  FIELD nom_Administrador LIKE Fac_header.nom_Administrador VALIDATE ~
  FIELD nro_administrador LIKE Fac_header.nro_administrador VALIDATE ~
  FIELD nro_cliente LIKE Fac_header.nro_cliente VALIDATE ~
  FIELD nro_cndventa LIKE Fac_header.nro_cndventa VALIDATE ~
  FIELD nro_comprob LIKE Fac_header.nro_comprob VALIDATE ~
  FIELD nro_contrato LIKE Fac_header.nro_contrato VALIDATE ~
  FIELD nro_deposito LIKE Fac_header.nro_deposito VALIDATE ~
  FIELD nro_domicilio LIKE Fac_header.nro_domicilio VALIDATE ~
  FIELD nro_entidad LIKE Fac_header.nro_entidad VALIDATE ~
  FIELD nro_factura LIKE Fac_header.nro_factura VALIDATE ~
  FIELD nro_moneda LIKE Fac_header.nro_moneda VALIDATE ~
  FIELD nro_obra LIKE Fac_header.nro_obra VALIDATE ~
  FIELD nro_ocm LIKE Fac_header.nro_ocm VALIDATE ~
  FIELD nro_remito LIKE Fac_header.nro_remito VALIDATE ~
  FIELD nro_transaccion LIKE Fac_header.nro_transaccion VALIDATE ~
  FIELD nro_usuario LIKE Fac_header.nro_usuario VALIDATE ~
  FIELD nro_vendedor LIKE Fac_header.nro_vendedor VALIDATE ~
  FIELD num_sucursal LIKE Fac_header.num_sucursal VALIDATE ~
  FIELD observacion LIKE Fac_header.observacion VALIDATE ~
  FIELD origen LIKE Fac_header.origen VALIDATE ~
  FIELD pc_name LIKE Fac_header.pc_name VALIDATE ~
  FIELD prc_canje LIKE Fac_header.prc_canje VALIDATE ~
  FIELD prf_comprob LIKE Fac_header.prf_comprob VALIDATE ~
  FIELD proc_estad LIKE Fac_header.proc_estad VALIDATE ~
  FIELD rige_hasta LIKE Fac_header.rige_hasta VALIDATE ~
  FIELD texto_condicion_venta LIKE Fac_header.texto_condicion_venta VALIDATE ~
  FIELD texto_iva LIKE Fac_header.texto_iva VALIDATE ~
  FIELD tip_comprob LIKE Fac_header.tip_comprob VALIDATE ~
  FIELD ultima_linea LIKE Fac_header.ultima_linea VALIDATE 
