DEFINE VARIABLE v-permisos AS CHARACTER INITIAL "A,B*,C" FORMAT "X(40)".
DEFINE VARIABLE v-sector AS CHARACTER INITIAL "B.67.AQS" FORMAT "X(40)".

REPEAT:
    UPDATE v-sector COLON 20 SKIP v-permisos COLON 20 WITH SIDE-LABELS .
    DISPLAY CAN-DO(v-permisos,v-sector) COLON 20.
END.

