DEFINE BUTTON btn_PROXIMO
     LABEL "->":L IMAGE FILE "BTN-RIGHT-ARROW"
     SIZE 4 BY 1 FONT 10.

DEFINE BUTTON btn_ANTERIOR
     LABEL "<-":L IMAGE FILE "BTN-LEFT-ARROW"
     SIZE 4 BY 1 FONT 10.
