{RUNCREMA.I "Acumulado_caja"}                                                   
{RUNCREMA.I "Acumulado_ccte"}                                                   
{RUNCREMA.I "Acumulado_ccte_prv"}                                               
{RUNCREMA.I "Acumulado_ctapsp"}                                                 
{RUNCREMA.I "Acumulado_cuenta"}                                                 
{RUNCREMA.I "Acumulado_pagos"}                                                  
{RUNCREMA.I "Acumulado_retemp"}                                                 
{RUNCREMA.I "Acumulado_stock"}                                                  
{RUNCREMA.I "Acum_ventas"}                                                      
{RUNCREMA.I "Ajusteinv_dt"}                                                     
{RUNCREMA.I "Ajusteinv_hd"}                                                     
{RUNCREMA.I "Anticipo_sue"}                                                     
{RUNCREMA.I "Aplicacion_pagos"}                                                 
{RUNCREMA.I "Aplicacion_pagos_prv"}                                             
{RUNCREMA.I "Aps_detalle"}                                                      
{RUNCREMA.I "Aps_header"}                                                       
{RUNCREMA.I "Aps_totales"}                                                      
{RUNCREMA.I "Articulo-deposito"}                                                
{RUNCREMA.I "Articulo-proveedor"}                                               
{RUNCREMA.I "Asiento_auditoria"}                                                
{RUNCREMA.I "Asn_detalle"}                                                      
{RUNCREMA.I "Asn_header"}                                                       
{RUNCREMA.I "Asn_totales"}                                                      
{RUNCREMA.I "Aud_liquidacion"}                                                  
{RUNCREMA.I "Boleta_deposito_dt"}                                               
{RUNCREMA.I "Boleta_deposito_hd"}                                               
{RUNCREMA.I "Caja-imputacion"}                                                  
{RUNCREMA.I "Caj_detalle"}                                                      
{RUNCREMA.I "Caj_header"}                                                       
{RUNCREMA.I "Cct_envases"}                                                      
{RUNCREMA.I "Cct_stock"}                                                        
{RUNCREMA.I "Certificado_gan"}                                                  
{RUNCREMA.I "Certificado_ibr"}                                                  
{RUNCREMA.I "Certificado_iva"}                                                  
{RUNCREMA.I "Certificado_sus"}                                                  
{RUNCREMA.I "Cert_ibr-detalle"}                                                 
{RUNCREMA.I "Cert_iva-detalle"}                                                 
{RUNCREMA.I "Cert_sus-detalle"}                                                 
{RUNCREMA.I "Cheque"}                                                           
{RUNCREMA.I "Chequera"}                                                         
{RUNCREMA.I "Cierre_diario"}                                                    
{RUNCREMA.I "Concepto_empleado_ant"}                                            
{RUNCREMA.I "Conciliacion"}                                                     
{RUNCREMA.I "Concurso-requisicion"}                                             
{RUNCREMA.I "Concurso_cotiza"}                                                  
{RUNCREMA.I "Concurso_item"}                                                    
{RUNCREMA.I "Concurso_precios"}                                                 
{RUNCREMA.I "Copias_ocompra"}                                                   
{RUNCREMA.I "Copias_requisicion"}                                               
{RUNCREMA.I "Cta_cte"}                                                          
{RUNCREMA.I "Cta_cte_aduana"}                                                   
{RUNCREMA.I "Cta_cte_bco"}                                                      
{RUNCREMA.I "Cta_cte_com"}                                                      
{RUNCREMA.I "Cta_cte_emp"}                                                      
{RUNCREMA.I "Cta_cte_prv"}                                                      
{RUNCREMA.I "Cupon"}                                                            
{RUNCREMA.I "Datos_liq"}                                                        
{RUNCREMA.I "Detalle_liquido"}                                                  
{RUNCREMA.I "Dev_detalle"}                                                      
{RUNCREMA.I "Dev_header"}                                                       
{RUNCREMA.I "Embarque-oci"}                                                     
{RUNCREMA.I "Emb_detalle_prv"}                                                  
{RUNCREMA.I "Emb_header_prv"}                                                   
{RUNCREMA.I "Emb_prv-gasto"}                                                    
{RUNCREMA.I "Empleado-ddjj"}                                                    
{RUNCREMA.I "Empleado-ddjj_ant"}                                                
{RUNCREMA.I "Especificacion_detalle"}                                           
{RUNCREMA.I "Especif_detlcontrato"}                                             
{RUNCREMA.I "Especif_detlpedido"}                                               
{RUNCREMA.I "Especif_headcontrato"}                                             
{RUNCREMA.I "Especif_headpedido"}                                               
{RUNCREMA.I "Especif_ocompra"}                                                  
{RUNCREMA.I "Especif_requisicion"}                                              
{RUNCREMA.I "Estado_liquidacion"}                                               
{RUNCREMA.I "Estado_registrables"}                                              
{RUNCREMA.I "Extracto"}                                                         
{RUNCREMA.I "Factura-recepcion"}                                                
{RUNCREMA.I "Factura_contenedor"}                                               
{RUNCREMA.I "Factura_de_credito"}                                               
{RUNCREMA.I "Factura_documentacion"}                                            
{RUNCREMA.I "Factura_gastos"}                                                   
{RUNCREMA.I "Fac_cli-gasto"}                                                    
{RUNCREMA.I "Fac_detalle"}                                                      
{RUNCREMA.I "Fac_detalle-bon"}                                                  
{RUNCREMA.I "Fac_detalle_impuesto"}                                             
{RUNCREMA.I "Fac_detalle_prv"}                                                  
{RUNCREMA.I "Fac_detalle_prv_bon"}                                              
{RUNCREMA.I "Fac_detalle_prv_impuesto"}                                         
{RUNCREMA.I "Fac_header"}                                                       
{RUNCREMA.I "Fac_header-bon"}                                                   
{RUNCREMA.I "Fac_header_impuesto"}                                              
{RUNCREMA.I "Fac_header_prv"}                                                   
{RUNCREMA.I "Fac_header_prv_bon"}                                               
{RUNCREMA.I "Fac_header_prv_impuesto"}                                          
{RUNCREMA.I "Fac_prv-gasto"}                                                    
{RUNCREMA.I "Franco_empleado"}                                                  
{RUNCREMA.I "Hst_domicilio"}                                                    
{RUNCREMA.I "Hst_estadoregis"}                                                  
{RUNCREMA.I "Hst_grupofam"}                                                     
{RUNCREMA.I "Hst_ocompra"}                                                      
{RUNCREMA.I "Hst_pedido"}                                                       
{RUNCREMA.I "Hst_rendgastos"}                                                   
{RUNCREMA.I "Hst_requisicion"}                                                  
{RUNCREMA.I "Ingresoaplanta"}                                                   
{RUNCREMA.I "Leyenda_factura"}                                                  
{RUNCREMA.I "Liquidacion"}                                                      
{RUNCREMA.I "Liq_detalle"}                                                      
{RUNCREMA.I "Liq_header"}                                                       
{RUNCREMA.I "Logmenu"}                                                          
{RUNCREMA.I "Logusuario"}                                                       
{RUNCREMA.I "Lote-factura"}                                                     
{RUNCREMA.I "Lote_pago"}                                                        
{RUNCREMA.I "Lst_estadlin"}                                                     
{RUNCREMA.I "Lst_sumysal"}                                                      
{RUNCREMA.I "Novedad-ocint"}                                                    
{RUNCREMA.I "Novedad-ocompra"}                                                  
{RUNCREMA.I "Novedad-opago"}                                                    
{RUNCREMA.I "Novedad-requisicion"}                                              
{RUNCREMA.I "Oci_detalle"}                                                      
{RUNCREMA.I "Oci_detalle_entr"}                                                 
{RUNCREMA.I "Oci_header"}                                                       
{RUNCREMA.I "Ocm_detalle"}                                                      
{RUNCREMA.I "Ocm_detalle_entr"}                                                 
{RUNCREMA.I "Ocm_header"}                                                       
{RUNCREMA.I "Ofabrica_dt"}                                                      
{RUNCREMA.I "Ofabrica_hd"}                                                      
{RUNCREMA.I "Ofabrica_parteprod"}                                               
{RUNCREMA.I "Opg_detalle"}                                                      
{RUNCREMA.I "Opg_header"}                                                       
{RUNCREMA.I "Parteprod_dt"}                                                     
{RUNCREMA.I "Parteprod_hd"}                                                     
{RUNCREMA.I "Parte_diario"}                                                     
{RUNCREMA.I "Parte_novedades"}                                                  
{RUNCREMA.I "Partida"}                                                          
{RUNCREMA.I "Partida-deposito"}                                                 
{RUNCREMA.I "Pedido_bonificacion"}                                              
{RUNCREMA.I "Pedido_credencial"}                                                
{RUNCREMA.I "Pedido_documentacion"}                                             
{RUNCREMA.I "Ped_detalle"}                                                      
{RUNCREMA.I "Ped_detalle-bon"}                                                  
{RUNCREMA.I "Ped_detalle_entr"}                                                 
{RUNCREMA.I "Ped_detalle_impuesto"}                                             
{RUNCREMA.I "Ped_header"}                                                       
{RUNCREMA.I "Ped_header-bon"}                                                   
{RUNCREMA.I "Ped_header_impuesto"}                                              
{RUNCREMA.I "Planprod_dt"}                                                      
{RUNCREMA.I "Planprod_hd"}                                                      
{RUNCREMA.I "Rango_liquidacion"}                                                
{RUNCREMA.I "Rcb_detalle"}                                                      
{RUNCREMA.I "Rcb_header"}                                                       
{RUNCREMA.I "Recepcion-ocint"}                                                  
{RUNCREMA.I "Recepcion-ocompra"}                                                
{RUNCREMA.I "Rec_detalle"}                                                      
{RUNCREMA.I "Rec_header"}                                                       
{RUNCREMA.I "Registrable-contrato"}                                             
{RUNCREMA.I "Registrable-factura"}                                              
{RUNCREMA.I "Registrable-pedido"}                                               
{RUNCREMA.I "Registrable-remito"}                                               
{RUNCREMA.I "Registrable-remprov"}                                              
{RUNCREMA.I "Registrable-solicitud"}                                            
{RUNCREMA.I "Registrable-transdep"}                                             
{RUNCREMA.I "Registrable_vale"}                                                 
{RUNCREMA.I "Regreso_solicitud"}                                                
{RUNCREMA.I "Remito-factura"}                                                   
{RUNCREMA.I "Remito-factura_prv"}                                               
{RUNCREMA.I "Remito-pedido"}                                                    
{RUNCREMA.I "Remito_contenedor"}                                                
{RUNCREMA.I "Remito_documentacion"}                                             
{RUNCREMA.I "Rem_detalle"}                                                      
{RUNCREMA.I "Rem_detalle-bon"}                                                  
{RUNCREMA.I "Rem_detalle_prv"}                                                  
{RUNCREMA.I "Rem_header"}                                                       
{RUNCREMA.I "Rem_header-bon"}                                                   
{RUNCREMA.I "Rem_header_prv"}                                                   
{RUNCREMA.I "Rendgastos_dt"}                                                    
{RUNCREMA.I "Rendgastos_hd"}                                                    
{RUNCREMA.I "Rendicion_dt"}                                                     
{RUNCREMA.I "Rendicion_hd"}                                                     
{RUNCREMA.I "Requisicion-ocompra"}                                              
{RUNCREMA.I "Rescuenta_dt"}                                                     
{RUNCREMA.I "Rescuenta_hd"}                                                     
{RUNCREMA.I "Rqs_detalle"}                                                      
{RUNCREMA.I "Rqs_detalle_entr"}                                                 
{RUNCREMA.I "Rqs_header"}                                                       
{RUNCREMA.I "Saldos_x_cuenta"}                                                  
{RUNCREMA.I "Sre_detalle"}                                                      
{RUNCREMA.I "Sre_header"}                                                       
{RUNCREMA.I "Sub_detalle_bco"}                                                  
{RUNCREMA.I "Sub_detalle_inv"}                                                  
{RUNCREMA.I "Sub_detalle_prv"}                                                  
{RUNCREMA.I "Sub_detalle_syj"}                                                  
{RUNCREMA.I "Sub_detalle_vta"}                                                  
{RUNCREMA.I "Sub_header_bco"}                                                   
{RUNCREMA.I "Sub_header_inv"}                                                   
{RUNCREMA.I "Sub_header_prv"}                                                   
{RUNCREMA.I "Sub_header_syj"}                                                   
{RUNCREMA.I "Sub_header_vta"}                                                   
{RUNCREMA.I "Tmp_detalle"}                                                      
{RUNCREMA.I "Tmp_header"}                                                       
{RUNCREMA.I "Total-liquidacion"}                                                
{RUNCREMA.I "Transdep_dt"}                                                      
{RUNCREMA.I "Transdep_hd"}                                                      
{RUNCREMA.I "Transfer-Requisicion"}                                             
{RUNCREMA.I "Vale-Requisicion"}                                                 
{RUNCREMA.I "Valeinv_dt"}                                                       
{RUNCREMA.I "Valeinv_hd"}                                                       
{RUNCREMA.I "Valor"}                                                            
{RUNCREMA.I "X_Calculo"}                                                        
/* */
{DEFPROCD.I "Acumulado_caja"}                                                   
{DEFPROCD.I "Acumulado_ccte"}                                                   
{DEFPROCD.I "Acumulado_ccte_prv"}                                               
{DEFPROCD.I "Acumulado_ctapsp"}                                                 
{DEFPROCD.I "Acumulado_cuenta"}                                                 
{DEFPROCD.I "Acumulado_pagos"}                                                  
{DEFPROCD.I "Acumulado_retemp"}                                                 
{DEFPROCD.I "Acumulado_stock"}                                                  
{DEFPROCD.I "Acum_ventas"}                                                      
{DEFPROCD.I "Ajusteinv_dt"}                                                     
{DEFPROCD.I "Ajusteinv_hd"}                                                     
{DEFPROCD.I "Anticipo_sue"}                                                     
{DEFPROCD.I "Aplicacion_pagos"}                                                 
{DEFPROCD.I "Aplicacion_pagos_prv"}                                             
{DEFPROCD.I "Aps_detalle"}                                                      
{DEFPROCD.I "Aps_header"}                                                       
{DEFPROCD.I "Aps_totales"}                                                      
{DEFPROCD.I "Articulo-deposito"}                                                
{DEFPROCD.I "Articulo-proveedor"}                                               
{DEFPROCD.I "Asiento_auditoria"}                                                
{DEFPROCD.I "Asn_detalle"}                                                      
{DEFPROCD.I "Asn_header"}                                                       
{DEFPROCD.I "Asn_totales"}                                                      
{DEFPROCD.I "Aud_liquidacion"}                                                  
{DEFPROCD.I "Boleta_deposito_dt"}                                               
{DEFPROCD.I "Boleta_deposito_hd"}                                               
{DEFPROCD.I "Caja-imputacion"}                                                  
{DEFPROCD.I "Caj_detalle"}                                                      
{DEFPROCD.I "Caj_header"}                                                       
{DEFPROCD.I "Cct_envases"}                                                      
{DEFPROCD.I "Cct_stock"}                                                        
{DEFPROCD.I "Certificado_gan"}                                                  
{DEFPROCD.I "Certificado_ibr"}                                                  
{DEFPROCD.I "Certificado_iva"}                                                  
{DEFPROCD.I "Certificado_sus"}                                                  
{DEFPROCD.I "Cert_ibr-detalle"}                                                 
{DEFPROCD.I "Cert_iva-detalle"}                                                 
{DEFPROCD.I "Cert_sus-detalle"}                                                 
{DEFPROCD.I "Cheque"}                                                           
{DEFPROCD.I "Chequera"}                                                         
{DEFPROCD.I "Cierre_diario"}                                                    
{DEFPROCD.I "Concepto_empleado_ant"}                                            
{DEFPROCD.I "Conciliacion"}                                                     
{DEFPROCD.I "Concurso-requisicion"}                                             
{DEFPROCD.I "Concurso_cotiza"}                                                  
{DEFPROCD.I "Concurso_item"}                                                    
{DEFPROCD.I "Concurso_precios"}                                                 
{DEFPROCD.I "Copias_ocompra"}                                                   
{DEFPROCD.I "Copias_requisicion"}                                               
{DEFPROCD.I "Cta_cte"}                                                          
{DEFPROCD.I "Cta_cte_aduana"}                                                   
{DEFPROCD.I "Cta_cte_bco"}                                                      
{DEFPROCD.I "Cta_cte_com"}                                                      
{DEFPROCD.I "Cta_cte_emp"}                                                      
{DEFPROCD.I "Cta_cte_prv"}                                                      
{DEFPROCD.I "Cupon"}                                                            
{DEFPROCD.I "Datos_liq"}                                                        
{DEFPROCD.I "Detalle_liquido"}                                                  
{DEFPROCD.I "Dev_detalle"}                                                      
{DEFPROCD.I "Dev_header"}                                                       
{DEFPROCD.I "Embarque-oci"}                                                     
{DEFPROCD.I "Emb_detalle_prv"}                                                  
{DEFPROCD.I "Emb_header_prv"}                                                   
{DEFPROCD.I "Emb_prv-gasto"}                                                    
{DEFPROCD.I "Empleado-ddjj"}                                                    
{DEFPROCD.I "Empleado-ddjj_ant"}                                                
{DEFPROCD.I "Especificacion_detalle"}                                           
{DEFPROCD.I "Especif_detlcontrato"}                                             
{DEFPROCD.I "Especif_detlpedido"}                                               
{DEFPROCD.I "Especif_headcontrato"}                                             
{DEFPROCD.I "Especif_headpedido"}                                               
{DEFPROCD.I "Especif_ocompra"}                                                  
{DEFPROCD.I "Especif_requisicion"}                                              
{DEFPROCD.I "Estado_liquidacion"}                                               
{DEFPROCD.I "Estado_registrables"}                                              
{DEFPROCD.I "Extracto"}                                                         
{DEFPROCD.I "Factura-recepcion"}                                                
{DEFPROCD.I "Factura_contenedor"}                                               
{DEFPROCD.I "Factura_de_credito"}                                               
{DEFPROCD.I "Factura_documentacion"}                                            
{DEFPROCD.I "Factura_gastos"}                                                   
{DEFPROCD.I "Fac_cli-gasto"}                                                    
{DEFPROCD.I "Fac_detalle"}                                                      
{DEFPROCD.I "Fac_detalle-bon"}                                                  
{DEFPROCD.I "Fac_detalle_impuesto"}                                             
{DEFPROCD.I "Fac_detalle_prv"}                                                  
{DEFPROCD.I "Fac_detalle_prv_bon"}                                              
{DEFPROCD.I "Fac_detalle_prv_impuesto"}                                         
{DEFPROCD.I "Fac_header"}                                                       
{DEFPROCD.I "Fac_header-bon"}                                                   
{DEFPROCD.I "Fac_header_impuesto"}                                              
{DEFPROCD.I "Fac_header_prv"}                                                   
{DEFPROCD.I "Fac_header_prv_bon"}                                               
{DEFPROCD.I "Fac_header_prv_impuesto"}                                          
{DEFPROCD.I "Fac_prv-gasto"}                                                    
{DEFPROCD.I "Franco_empleado"}                                                  
{DEFPROCD.I "Hst_domicilio"}                                                    
{DEFPROCD.I "Hst_estadoregis"}                                                  
{DEFPROCD.I "Hst_grupofam"}                                                     
{DEFPROCD.I "Hst_ocompra"}                                                      
{DEFPROCD.I "Hst_pedido"}                                                       
{DEFPROCD.I "Hst_rendgastos"}                                                   
{DEFPROCD.I "Hst_requisicion"}                                                  
{DEFPROCD.I "Ingresoaplanta"}                                                   
{DEFPROCD.I "Leyenda_factura"}                                                  
{DEFPROCD.I "Liquidacion"}                                                      
{DEFPROCD.I "Liq_detalle"}                                                      
{DEFPROCD.I "Liq_header"}                                                       
{DEFPROCD.I "Logmenu"}                                                          
{DEFPROCD.I "Logusuario"}                                                       
{DEFPROCD.I "Lote-factura"}                                                     
{DEFPROCD.I "Lote_pago"}                                                        
{DEFPROCD.I "Lst_estadlin"}                                                     
{DEFPROCD.I "Lst_sumysal"}                                                      
{DEFPROCD.I "Novedad-ocint"}                                                    
{DEFPROCD.I "Novedad-ocompra"}                                                  
{DEFPROCD.I "Novedad-opago"}                                                    
{DEFPROCD.I "Novedad-requisicion"}                                              
{DEFPROCD.I "Oci_detalle"}                                                      
{DEFPROCD.I "Oci_detalle_entr"}                                                 
{DEFPROCD.I "Oci_header"}                                                       
{DEFPROCD.I "Ocm_detalle"}                                                      
{DEFPROCD.I "Ocm_detalle_entr"}                                                 
{DEFPROCD.I "Ocm_header"}                                                       
{DEFPROCD.I "Ofabrica_dt"}                                                      
{DEFPROCD.I "Ofabrica_hd"}                                                      
{DEFPROCD.I "Ofabrica_parteprod"}                                               
{DEFPROCD.I "Opg_detalle"}                                                      
{DEFPROCD.I "Opg_header"}                                                       
{DEFPROCD.I "Parteprod_dt"}                                                     
{DEFPROCD.I "Parteprod_hd"}                                                     
{DEFPROCD.I "Parte_diario"}                                                     
{DEFPROCD.I "Parte_novedades"}                                                  
{DEFPROCD.I "Partida"}                                                          
{DEFPROCD.I "Partida-deposito"}                                                 
{DEFPROCD.I "Pedido_bonificacion"}                                              
{DEFPROCD.I "Pedido_credencial"}                                                
{DEFPROCD.I "Pedido_documentacion"}                                             
{DEFPROCD.I "Ped_detalle"}                                                      
{DEFPROCD.I "Ped_detalle-bon"}                                                  
{DEFPROCD.I "Ped_detalle_entr"}                                                 
{DEFPROCD.I "Ped_detalle_impuesto"}                                             
{DEFPROCD.I "Ped_header"}                                                       
{DEFPROCD.I "Ped_header-bon"}                                                   
{DEFPROCD.I "Ped_header_impuesto"}                                              
{DEFPROCD.I "Planprod_dt"}                                                      
{DEFPROCD.I "Planprod_hd"}                                                      
{DEFPROCD.I "Rango_liquidacion"}                                                
{DEFPROCD.I "Rcb_detalle"}                                                      
{DEFPROCD.I "Rcb_header"}                                                       
{DEFPROCD.I "Recepcion-ocint"}                                                  
{DEFPROCD.I "Recepcion-ocompra"}                                                
{DEFPROCD.I "Rec_detalle"}                                                      
{DEFPROCD.I "Rec_header"}                                                       
{DEFPROCD.I "Registrable-contrato"}                                             
{DEFPROCD.I "Registrable-factura"}                                              
{DEFPROCD.I "Registrable-pedido"}                                               
{DEFPROCD.I "Registrable-remito"}                                               
{DEFPROCD.I "Registrable-remprov"}                                              
{DEFPROCD.I "Registrable-solicitud"}                                            
{DEFPROCD.I "Registrable-transdep"}                                             
{DEFPROCD.I "Registrable_vale"}                                                 
{DEFPROCD.I "Regreso_solicitud"}                                                
{DEFPROCD.I "Remito-factura"}                                                   
{DEFPROCD.I "Remito-factura_prv"}                                               
{DEFPROCD.I "Remito-pedido"}                                                    
{DEFPROCD.I "Remito_contenedor"}                                                
{DEFPROCD.I "Remito_documentacion"}                                             
{DEFPROCD.I "Rem_detalle"}                                                      
{DEFPROCD.I "Rem_detalle-bon"}                                                  
{DEFPROCD.I "Rem_detalle_prv"}                                                  
{DEFPROCD.I "Rem_header"}                                                       
{DEFPROCD.I "Rem_header-bon"}                                                   
{DEFPROCD.I "Rem_header_prv"}                                                   
{DEFPROCD.I "Rendgastos_dt"}                                                    
{DEFPROCD.I "Rendgastos_hd"}                                                    
{DEFPROCD.I "Rendicion_dt"}                                                     
{DEFPROCD.I "Rendicion_hd"}                                                     
{DEFPROCD.I "Requisicion-ocompra"}                                              
{DEFPROCD.I "Rescuenta_dt"}                                                     
{DEFPROCD.I "Rescuenta_hd"}                                                     
{DEFPROCD.I "Rqs_detalle"}                                                      
{DEFPROCD.I "Rqs_detalle_entr"}                                                 
{DEFPROCD.I "Rqs_header"}                                                       
{DEFPROCD.I "Saldos_x_cuenta"}                                                  
{DEFPROCD.I "Sre_detalle"}                                                      
{DEFPROCD.I "Sre_header"}                                                       
{DEFPROCD.I "Sub_detalle_bco"}                                                  
{DEFPROCD.I "Sub_detalle_inv"}                                                  
{DEFPROCD.I "Sub_detalle_prv"}                                                  
{DEFPROCD.I "Sub_detalle_syj"}                                                  
{DEFPROCD.I "Sub_detalle_vta"}                                                  
{DEFPROCD.I "Sub_header_bco"}                                                   
{DEFPROCD.I "Sub_header_inv"}                                                   
{DEFPROCD.I "Sub_header_prv"}                                                   
{DEFPROCD.I "Sub_header_syj"}                                                   
{DEFPROCD.I "Sub_header_vta"}                                                   
{DEFPROCD.I "Tmp_detalle"}                                                      
{DEFPROCD.I "Tmp_header"}                                                       
{DEFPROCD.I "Total-liquidacion"}                                                
{DEFPROCD.I "Transdep_dt"}                                                      
{DEFPROCD.I "Transdep_hd"}                                                      
{DEFPROCD.I "Transfer-Requisicion"}                                             
{DEFPROCD.I "Vale-Requisicion"}                                                 
{DEFPROCD.I "Valeinv_dt"}                                                       
{DEFPROCD.I "Valeinv_hd"}                                                       
{DEFPROCD.I "Valor"}                                                            
{DEFPROCD.I "X_Calculo"}                                                        
