OUTPUT TO PRINTER PAGE-SIZE 65.
PUT CONTROL "~033" + "&k4S".

FORM
   Mensaje.cdg_mensaje 
   Mensaje.tipo
   Mensaje.texto VIEW-AS EDITOR SIZE 50 BY 5 
   WITH FRAME A CENTERED DOWN STREAM-IO USE-TEXT
        TITLE "INGRESO DE MENSAJES" .

FOR EACH MENSAJE:
  DISPLAY Mensaje WITH FRAME A.
  DOWN WITH FRAME A. 
END.  

OUTPUT CLOSE.
