
{VPERSINM.I}
DEFINE INPUT PARAMETER RB_LIBRARY  AS CHARACTER NO-UNDO.
DEFINE INPUT PARAMETER RB_REPORT   AS CHARACTER NO-UNDO.
DEFINE INPUT PARAMETER cConnect    AS CHARACTER NO-UNDO.
DEFINE INPUT PARAMETER RB_INCLUDE  AS CHARACTER NO-UNDO.
DEFINE INPUT PARAMETER RB_FILTER   AS CHARACTER NO-UNDO.
DEFINE INPUT PARAMETER RB_MEMO     AS CHARACTER NO-UNDO.
DEFINE INPUT PARAMETER RB_PRINTER  AS CHARACTER NO-UNDO.
DEFINE INPUT PARAMETER RB_WPTR     AS CHARACTER NO-UNDO.
DEFINE INPUT PARAMETER RB_WPORT    AS CHARACTER NO-UNDO.
DEFINE INPUT PARAMETER RB_OUTFILE  AS CHARACTER NO-UNDO.

DEFINE INPUT PARAMETER RB_COPIES   AS INTEGER   NO-UNDO.
DEFINE INPUT PARAMETER RB_BEGPAGE  AS INTEGER   NO-UNDO.
DEFINE INPUT PARAMETER RB_ENDPAGE  AS INTEGER   NO-UNDO.
DEFINE INPUT PARAMETER RB_TEST     AS LOGICAL   NO-UNDO.
DEFINE INPUT PARAMETER RB_WTITLE   AS CHARACTER NO-UNDO.
DEFINE INPUT PARAMETER RB_DISPERR  AS LOGICAL   NO-UNDO.
DEFINE INPUT PARAMETER RB_STATUS   AS LOGICAL   NO-UNDO.
DEFINE INPUT PARAMETER RB_NOWAIT   AS LOGICAL   NO-UNDO.
DEFINE INPUT PARAMETER cOther      AS CHARACTER NO-UNDO.

DEFINE VARIABLE RB_DB        AS CHARACTER NO-UNDO.
DEFINE VARIABLE RB_USER      AS CHARACTER NO-UNDO.
DEFINE VARIABLE RB_PASSWORD  AS CHARACTER NO-UNDO.
DEFINE VARIABLE RB_SERVER    AS CHARACTER NO-UNDO.
DEFINE VARIABLE RB_HOST      AS CHARACTER NO-UNDO.
DEFINE VARIABLE RB_NETWORK   AS CHARACTER NO-UNDO.
DEFINE VARIABLE cEntry1      AS CHARACTER NO-UNDO.
DEFINE VARIABLE cEntry2      AS CHARACTER NO-UNDO.
DEFINE VARIABLE i            AS INTEGER   NO-UNDO.
DEFINE VARIABLE cTmp         AS CHARACTER NO-UNDO.
DEFINE VARIABLE do_wait      AS INTEGER   NO-UNDO.

i = 1.
DO WHILE (i < NUM-ENTRIES (cConnect," ")):
  assign
    cEntry1 = ENTRY (i, cConnect, " ")
    i = i + 1
    cEntry2 = ENTRY (i, cConnect, " ")
	 .

	 CASE (cEntry1):
	   WHEN "-db" THEN RB_DB        = cENTRY2.
	   WHEN "-U"  THEN RB_USER      = cENTRY2.
	   WHEN "-P"  THEN RB_PASSWORD  = cENTRY2.
	   WHEN "-S"  THEN RB_SERVER    = cENTRY2.
	   WHEN "-H"  THEN RB_HOST      = cENTRY2.
	   WHEN "-N"  THEN RB_NETWORK   = cENTRY2.
	 END.
    i = i + 1.
END.


IF (RB_PRINTER <> "D" and RB_PRINTER <> "?" and RB_PRINTER <> "") THEN
  RB_PRINTER = "A".

IF (RB_NETWORK = "(local)") THEN
  RB_NETWORK = "".
										 
output to "rbrun.txt" no-convert.

IF (cConnect <> "") THEN
    PUT UNFORMATTED "RB-DB-CONNECTION=" cConnect SKIP.

PUT UNFORMATTED "RB-DB="                 RB_DB       SKIP.
PUT UNFORMATTED "RB-SERVER="             RB_SERVER   SKIP.
PUT UNFORMATTED "RB-HOSTNAME="           RB_HOST     SKIP.
PUT UNFORMATTED "RB-NETWORK="            RB_NETWORK  SKIP.
PUT UNFORMATTED "RB-REPORT-NAME="        RB_REPORT   SKIP.
PUT UNFORMATTED "RB-REPORT-LIBRARY="     RB_LIBRARY  SKIP.
PUT UNFORMATTED "RB-PRINT-DESTINATION="  RB_PRINTER  SKIP.
PUT UNFORMATTED "RB-WINDOW-TITLE="       RB_WTITLE   SKIP.

cTmp = IF (RB_DISPERR = TRUE) THEN "T" ELSE "F".
PUT UNFORMATTED "RB-DISPLAY-ERRORS=" cTmp        SKIP.

cTmp = IF (RB_STATUS  = TRUE) THEN "T" ELSE "F".
PUT UNFORMATTED "RB-DISPLAY-STATUS="  cTmp        SKIP.
PUT UNFORMATTED "RB-MEMO-FILE="    RB_MEMO     SKIP.
PUT UNFORMATTED "RB-OUTPUT-FILE=" RB_OUTFILE  SKIP.
PUT UNFORMATTED "RB-PRINTER-NAME="    RB_WPTR     SKIP.
PUT UNFORMATTED "RB-PRINTER-PORT="   RB_WPORT    SKIP.

IF RB_BEGPAGE > 0 THEN
    PUT UNFORMATTED "RB-BEGIN-PAGE=" RB_BEGPAGE  SKIP.
IF RB_ENDPAGE > 0 THEN
    PUT UNFORMATTED "RB-END-PAGE=" RB_ENDPAGE  SKIP.

cTmp = IF (RB_TEST  = TRUE) THEN "T" ELSE "F".
PUT UNFORMATTED "RB-TEST-PATTERN="    cTmp        SKIP.
PUT UNFORMATTED "RB-NUMBER-COPIES="  RB_COPIES   SKIP.

PUT UNFORMATTED "RB-INCLUDE-RECORDS=" RB_INCLUDE  SKIP.

PUT UNFORMATTED "RB-FILTER="  RB_FILTER   SKIP.

i = 1.
DO WHILE (i <= NUM-ENTRIES (cOther,CHR(10))):
  ASSIGN
    cEntry1 = ENTRY (i, cOther, CHR(10))
    i = i + 1
	 .
  PUT UNFORMATTED cEntry1  SKIP.
END.

OUTPUT CLOSE.

IF (rb_nowait) THEN
    do_wait = 0.
ELSE
    do_wait = 1.

IF (RB_USER > "") THEN
  ASSIGN
    cTmp = "RBRUN /TTrbrun.txt /U" + RB_USER + " /P" + RB_PASSWORD.
ELSE
  ASSIGN
    cTmp = "RBRUN /TTrbrun.txt".

RUN ProExec (cTmp, INPUT 1, do_wait, /* current-window:hwnd, */ INPUT 5). /* 1=normal 2=minimized */

PROCEDURE ProExec EXTERNAL "PROEXEC.DLL": 
    DEFINE INPUT PARAMETER prog_name AS CHARACTER. 
    DEFINE INPUT PARAMETER prog_style AS SHORT. 
    DEFINE INPUT PARAMETER wait_for_me as SHORT.
    DEFINE INPUT PARAMETER num_seconds as SHORT.
END.
 