  DEFINE VARIABLE chApplication     AS COM-HANDLE NO-UNDO.
  DEFINE VARIABLE chReport          AS COM-HANDLE NO-UNDO.
  DEFINE VARIABLE chParamDefs       AS COM-HANDLE NO-UNDO.
  DEFINE VARIABLE chParamDef        AS COM-HANDLE NO-UNDO.
  DEFINE VARIABLE cFullPath         AS CHARACTER NO-UNDO. 
  DEFINE VARIABLE xFullPath         AS CHARACTER NO-UNDO. 
  DEFINE VARIABLE exportFileName    AS CHARACTER NO-UNDO. 

  DEFINE VARIABLE xfile             AS CHARACTER NO-UNDO.
  DEFINE VARIABLE ReportePath       AS CHAR NO-UNDO.
  DEFINE VARIABLE error_nro         AS INTEGER NO-UNDO.
  DEFINE VARIABLE FDESTC            AS CHARACTER NO-UNDO.
    RUN getparametro_c.p (INPUT "FDESTC" , OUTPUT FDESTC).
