
DEFINE {1} SHARED FRAME frm-logo 
     SKIP(1)
     btn_INV     AT 57 SKIP(0.0)
     BACKGROUND LOGOTIPO AT ROW 1 COL 1 /*SKIP(1)*/
     /*BACKGROUND   COMPUTEL AT ROW 9.5 COL 40 */        
     WITH CENTERED SIDE-LABELS NO-BOX KEEP-TAB-ORDER THREE-D.
