  DEFINE VARIABLE {&ROWID_TABLA} AS ROWID.
  RUN {&SELECCION} ( INPUT-OUTPUT {&ROWID_TABLA}, INPUT YES ).
  IF {&ROWID_TABLA} <> ?
  THEN DO:
       FIND {&TABLA} WHERE ROWID({&TABLA}) = {&ROWID_TABLA} NO-LOCK.
       {&V-CDG_TABLA} = {&TABLA}.{&CDG_TABLA}.
       DISPLAY {&V-CDG_TABLA}
               WITH FRAME {&FRAME-NAME}.
       &IF {&MOSTRAR_DSC}
       &THEN
       {&V-DSC_TABLA} = {&TABLA}.{&DSC_TABLA}.
       DISPLAY {&V-DSC_TABLA}
               WITH FRAME {&FRAME-NAME}.
       &ENDIF
       APPLY "TAB" TO SELF.
  END.
  RETURN NO-APPLY.
