PROCEDURE INICIAR_SESION:

  IF CURRENT-WINDOW <> MAIN-WINDOW THEN ASSIGN CURRENT-WINDOW = MAIN-WINDOW.

  IF cod_aut = 0 
  THEN DO:
     ENABLE  btn_INV
             WITH FRAME frm-logo.  
  END. 
  ELSE DO:
     DISABLE btn_INV
             WITH FRAME frm-logo.  
  END. 

  MENU Principal:SENSITIVE = YES.

  IF MAIN-WINDOW:MENUBAR <> MENU Principal:HANDLE
  THEN DO:
     MAIN-WINDOW:TITLE = titulo.     
     MAIN-WINDOW:MENUBAR = MENU Principal:HANDLE.
  END.   

  SUB-MENU  Archivo:SENSITIVE = YES.
  SUB-MENU  Seguridad:SENSITIVE = CONNECTED("SIC").
  MENU-ITEM Conectar:SENSITIVE IN MENU Archivo = YES.
  MENU-ITEM Desconectar:SENSITIVE IN MENU Archivo = CONNECTED("SIC").
  MENU-ITEM Datos:SENSITIVE IN MENU Archivo = CONNECTED("SIC").
  MENU-ITEM Empresa:SENSITIVE IN MENU Archivo = CONNECTED("SIC").
  MENU-ITEM Salir:SENSITIVE IN MENU Archivo = YES.

  STATUS INPUT OFF IN WINDOW MAIN-WINDOW.
  VIEW FRAME frm-logo.

END PROCEDURE.
