DEFINE VARIABLE modo_emision        AS INTEGER INITIAL 0.
DEFINE VARIABLE indep               AS INTEGER INITIAL 0.
DEFINE VARIABLE rem_y_fac           AS INTEGER INITIAL 1.
DEFINE VARIABLE fac_y_rem           AS INTEGER INITIAL 2.
DEFINE VARIABLE lado_a_lado         AS INTEGER INITIAL 3.
