DEFINE VARIABLE str_debitan     AS CHARACTER INITIAL "FA,FB,FC,FE,FK,DA,DB,DC,DE,DK,SI,DI,DX,DR,DS".
DEFINE VARIABLE str_debitan_prv AS CHARACTER INITIAL "OP,DI,GP,CA,CB,CC,DP".
DEFINE VARIABLE str_debitan_bco AS CHARACTER INITIAL "CH,DB,EX,RVL".
DEFINE VARIABLE str_debitan_inv AS CHARACTER INITIAL "TS,VS,DS,AN,RM,DP".
DEFINE VARIABLE str_debitan_com AS CHARACTER INITIAL "PV,PC,AV,AC,DV,DC".

/* RUN cargar_debitan.p ( OUTPUT str_debitan ). */
