ON ".", MOUSE-SELECT-DBLCLICK, MOUSE-MENU-DOWN OF {&TABLA}.{&CODIGO}  IN FRAME {&FRAME-INGRESO}
DO:

  RUN {&RUTINA}.P (OUTPUT {&ROWID-TABLA}, INPUT {&ALT-MOD}).
  IF {&ROWID-TABLA} <> ?
  THEN DO:
     FIND {&TABLA} WHERE ROWID({&TABLA}) = {&ROWID-TABLA} /* AND
          {&TABLA}.{&CODIGO} = area.cdg_area */
          &IF DEFINED(EXCLUSIVO)
          &THEN EXCLUSIVE-LOCK
          &ELSE NO-LOCK
          &ENDIF
          .
     DISPLAY {&TABLA}.{&CODIGO} WITH FRAME {&FRAME-INGRESO}.
     APPLY "RETURN" TO {&TABLA}.{&CODIGO} IN FRAME {&FRAME-INGRESO}.
     RETURN NO-APPLY.
  END.  
END.   

&IF {&TRADUCIR} &THEN

ON ENTRY OF {&TABLA}.{&CODIGO}  IN FRAME {&FRAME-INGRESO}
DO:
  ant_ROWID = ROWID({&TABLA}). 
END.  

ON RETURN, TAB OF {&TABLA}.{&CODIGO}  IN FRAME {&FRAME-INGRESO}
DO:
    
   FIND {&TABLA} USING {&CODIGO} 
     &IF DEFINED(EXCLUSIVO)
     &THEN EXCLUSIVE-LOCK
     &ELSE NO-LOCK
     &ENDIF      
     NO-ERROR.
        
   IF NOT AVAILABLE {&TABLA}
   THEN DO:
      BELL.
      MESSAGE "El codigo indicado no existe en la tabla maestra"
        VIEW-AS ALERT-BOX ERROR BUTTONS OK.
      RETURN NO-APPLY.
   END.
   ELSE DO:
      no_aplicar = NO.
      {&ROWID-TABLA} = ROWID({&TABLA}).
&IF {&MOSTRAR} &THEN   
      DISPLAY {&TABLA}.{&NOMBRE} WITH FRAME {&FRAME-INGRESO}.
&ENDIF
    END.

&IF DEFINED(PROCESO) &THEN
   IF ant_ROWID <> ROWID({&TABLA}) 
   THEN DO:
        RUN {&PROCESO}.
   END.     
&ENDIF   

   IF no_aplicar THEN RETURN NO-APPLY.

END.

&ENDIF

ON F7 OF {&TABLA}.{&CODIGO}  IN FRAME {&FRAME-INGRESO}
DO:
  /*
  &IF DEFINED(NO-HIDE) EQ 0
  &THEN
  HIDE FRAME {&FRAME-INGRESO}.
  &ENDIF
  */
  &IF DEFINED(HAY-MENU) 
  &THEN
  MENU Principal:SENSITIVE = NO.
  &ENDIF
  {&ULT_REGISTRO} = ?.
  RUN {&ALTA-MODIF}.P (INPUT 1).
  RUN PONER_SESION.  
  IF {&ULT_REGISTRO} <> ?
  THEN DO:
     ant_ROWID = ?.
     FIND {&TABLA} WHERE ROWID({&TABLA}) = {&ULT_REGISTRO} NO-LOCK.
     DISPLAY {&TABLA}.{&CODIGO} WITH FRAME {&FRAME-INGRESO}.
     APPLY "RETURN" TO {&TABLA}.{&CODIGO} IN FRAME {&FRAME-INGRESO}.
  END.
  ELSE DO:
     /*
     &IF DEFINED(NO-HIDE) EQ 0
     &THEN
     */
     VIEW FRAME {&FRAME-INGRESO}.
     /*&ENDIF*/
     APPLY "ENTRY" TO {&TABLA}.{&CODIGO} IN FRAME {&FRAME-INGRESO}.
  END.   
  RETURN NO-APPLY.   
END.  

ON F8 OF {&TABLA}.{&CODIGO}  IN FRAME {&FRAME-INGRESO}
DO:
  IF NOT AVAILABLE {&TABLA}
  THEN DO:
     RUN PONMENSJ.P (INPUT "HELP001").
  END.   
  ELSE DO:
     HIDE FRAME {&FRAME-INGRESO}.
     {&ULT_REGISTRO} = ROWID({&TABLA}).
     RUN {&ALTA-MODIF}.P (INPUT 2).
     RUN PONER_SESION.
     IF {&ULT_REGISTRO} <> ?
     THEN DO:
        ant_ROWID = ?.     
        FIND {&TABLA} WHERE ROWID({&TABLA}) = {&ULT_REGISTRO} NO-LOCK.
        DISPLAY {&TABLA}.{&CODIGO} WITH FRAME {&FRAME-INGRESO}.
        APPLY "RETURN" TO {&TABLA}.{&CODIGO} IN FRAME {&FRAME-INGRESO}.
     END.
     ELSE DO:
        VIEW FRAME {&FRAME-INGRESO}.
        APPLY "ENTRY" TO {&TABLA}.{&CODIGO} IN FRAME {&FRAME-INGRESO}.
     END.   
  END.   
  RETURN NO-APPLY.   
END.  
