ON ".", MOUSE-SELECT-DBLCLICK OF {&VAR-CODIGO}  IN FRAME {&FRAME-INGRESO}
DO:

  RUN {&RUTINA}.P (OUTPUT {&ROWID-TABLA}, INPUT NO).
  IF {&ROWID-TABLA} <> ?
  THEN DO:
     FIND {&TABLA} WHERE ROWID({&TABLA}) = {&ROWID-TABLA} NO-LOCK.
     DISPLAY {&TABLA}.{&CODIGO} @ {&VAR-CODIGO} WITH FRAME {&FRAME-INGRESO}.
     APPLY "RETURN" TO {&VAR-CODIGO} IN FRAME {&FRAME-INGRESO}.
     RETURN NO-APPLY.
  END.  
END.   

ON RETURN, TAB OF {&VAR-CODIGO}  IN FRAME {&FRAME-INGRESO}
DO:
    
   ASSIGN {&VAR-CODIGO}.
   FIND {&TABLA} WHERE {&TABLA}.{&CODIGO} = {&VAR-CODIGO} NO-LOCK NO-ERROR.
        
   IF NOT AVAILABLE {&TABLA}
   THEN DO:
      BELL.
      MESSAGE "El codigo indicado no existe en la tabla maestra"
        VIEW-AS ALERT-BOX ERROR BUTTONS OK.
      RETURN NO-APPLY.
   END.
   ELSE DO:
      {&ROWID-TABLA} = ROWID({&TABLA}).
      {&VAR-NOMBRE} = {&TABLA}.{&NOMBRE}.
      DISPLAY {&VAR-NOMBRE} WITH FRAME {&FRAME-INGRESO}.
      &IF DEFINED(PROCESO-CUENTA)
      &THEN
      no_aplicar = NO.
      {&PROCESO-CUENTA}.
      IF no_aplicar THEN RETURN NO-APPLY.
      &ENDIF
   END.

END.

