DEFINE VARIABLE stped_creditoins AS CHARACTER FORMAT "X(2)" INITIAL "D1".
DEFINE VARIABLE stped_deuvencida AS CHARACTER FORMAT "X(2)" INITIAL "D2".
DEFINE VARIABLE stped_chequerech AS CHARACTER FORMAT "X(2)" INITIAL "D3".
DEFINE VARIABLE stped_cndventano AS CHARACTER FORMAT "X(2)" INITIAL "D4".
DEFINE VARIABLE stped_listapreno AS CHARACTER FORMAT "X(2)" INITIAL "D5".
DEFINE VARIABLE stped_nohaystock AS CHARACTER FORMAT "X(2)" INITIAL "SI".
DEFINE VARIABLE stped_aprobado   AS CHARACTER FORMAT "X(2)" INITIAL "AA".
DEFINE VARIABLE stped_aprmanual  AS CHARACTER FORMAT "X(2)" INITIAL "AM".
