{foreachborra.i "Proveedor"}
{foreachborra.i "Articulo"}
{foreachborra.i "Cliente"}
{foreachborra.i "Domicilio"}
{foreachborra.i "Domicilio_prv"}

{foreachborra.i "Proveedor_cndventa"}
{foreachborra.i "Cliente_cndventa"}
{foreachborra.i "Articulo_precio"}
{foreachborra.i "Partida"}
{foreachborra.i "Acumulado_cuenta"}
{foreachborra.i "Cuenta_bancaria"}
{foreachborra.i "Empleado"}
{foreachborra.i "Cotizacion"}
{foreachborra.i "Entidad"}
{foreachborra.i "Periodo_fiscal"}
{foreachborra.i "Ejercicio_fiscal"}
{foreachborra.i "Cliente-bonificacion"}
{foreachborra.i "Articulo-impuesto"}
{foreachborra.i "Bduso"}
{foreachborra.i "Partida-deposito"}
{foreachborra.i "Articulo-deposito"}
{foreachborra.i "Punto-venta"}
{foreachborra.i "Cliente-bonxarticulo"}
{foreachborra.i "Cliente-observacion"}
{foreachborra.i "Parametro-excep"}
{foreachborra.i "Registrable"}
{foreachborra.i "Cobrador_ptovta"}
{foreachborra.i "Certificado_sus"}
{foreachborra.i "Vendedor_escala"}
{foreachborra.i "Vendedor_cliente"}
{foreachborra.i "Vendedor_articliente"}
{foreachborra.i "Entidad_distribucion"}
{foreachborra.i "Permiso-transaccion"}
{foreachborra.i "Ctapsp-cuenta"}
{foreachborra.i "Contrato_hd"}
{foreachborra.i "Clase_de_Obra"}
{foreachborra.i "Clase_de_Entidad"}
{foreachborra.i "Proveedor_viapago"}
{foreachborra.i "Factura_de_credito"}
{foreachborra.i "Saldos_x_cuenta"}
{foreachborra.i "Cliente_excencion"}
{foreachborra.i "Vigencia_precios"}
{foreachborra.i "Cierre_diario"}
{foreachborra.i "Vigencia_cai"}
{foreachborra.i "Vigencia_cyorden"}
{foreachborra.i "Tipo_puntovta"}
{foreachborra.i "Cuenta-usuarios"}
{foreachborra.i "Linea"}
{foreachborra.i "Producto"}
{foreachborra.i "Proveedor_excencion"}
{foreachborra.i "Afiliado"}
{foreachborra.i "Plan"}
{foreachborra.i "Grupofam"}
{foreachborra.i "Grupo-domicilio"}
{foreachborra.i "Hst_grupofam"}
{foreachborra.i "Hst_domicilio"}
{foreachborra.i "Plan-capita"}
{foreachborra.i "Pedido_credencial"}
{foreachborra.i "Sre_header"}
{foreachborra.i "Logmenu"}
{foreachborra.i "Logusuario"}
{foreachborra.i "Articulo_tiporendicion"}
{foreachborra.i "Proveedor_articulo"}
{foreachborra.i "Imputacion_difcambios"}
{foreachborra.i "Autoriza_transaccion"}
{foreachborra.i "Vendedor_obj_general"}
{foreachborra.i "Vendedor_obj_zona"}
{foreachborra.i "Vendedor_objetivo"}
