DEFINE VARIABLE lista AS CHARACTER VIEW-AS SELECTION-LIST INNER-CHARS 70 INNER-LINES 15.
DEFINE VARIABLE x     AS CHARACTER VIEW-AS EDITOR SIZE 60 BY 5.
DEFINE VARIABLE j     AS INTEGER.
DEFINE VARIABLE ok    AS LOGICAL.

FORM
 lista FGCOLOR 0 BGCOLOR 15 NO-LABEL
 WITH FRAME a NO-LABEL THREE-D TITLE "Propath... Oprima F2 para continuar"
 VIEW-AS DIALOG-BOX.

x = PROPATH.               
DO j = 1 TO NUM-ENTRIES(x,";"):
   ok = lista:ADD-LAST(ENTRY(j,x,";")).
END.

DISPLAY lista WITH FRAME a.
ENABLE lista WITH FRAME a. 
WAIT-FOR F2 OF FRAME a.
HIDE FRAME a NO-PAUSE. 
