PROCEDURE CONVERTIR_FECHA:

  DEFINE INPUT  PARAMETER dia   AS CHARACTER.
  DEFINE INPUT  PARAMETER mes   AS CHARACTER.
  DEFINE INPUT  PARAMETER ano   AS CHARACTER.
  DEFINE OUTPUT PARAMETER donde AS DATE.
  DEFINE INPUT  PARAMETER quien AS CHARACTER.  
  DEFINE VARIABLE f AS DATE.
  
  IF mes = "99" 
  THEN DO:
     mes = "12".
     ano = "9999".
  END.   

  f = DATE(dia + "/" + mes + "/" + "19" + ano ) NO-ERROR.
  IF NOT ERROR-STATUS:ERROR
  THEN DO:
     donde = f.
  END.
  
END PROCEDURE.     
