&GLOBAL-DEFINE NT_MODULOS 21

DEFINE VARIABLE directorios AS CHARACTER EXTENT {&NT_MODULOS} 
  INITIAL ["aba",
           "adp",
           "afi",
           "bas",
           "bdu",
           "com",
           "cps",
           "cpy",           
           "cxc",
           "cxp",
           "dsp",
           "exp",
           "fac",
           "gla",
           "imp",
           "inv",
           "prd",
           "rgv",
           "seg",
           "tes",
           "utl"].
DEFINE VARIABLE accionar AS LOGICAL EXTENT {&NT_MODULOS} VIEW-AS TOGGLE-BOX
  LABEL     "ABA - Abastecimientos",
            "ADP - Personal",
            "AFI - Afiliados",
            "BAS - Sicbase",
            "BDU - Bienes de Uso",
            "COM - Compras",
            "CPS - Control Presupuestario",
            "CPY - Control de Proyectos",
            "CXC - Cuentas x Cobrar",
            "CXP - Cuentas x Pagar",
            "DSP - Despacho",
            "EXP - Exportaciones",
            "FAC - Facturacion",
            "GLA - Contabilidad Analitica",
            "IMP - Importaciones",
            "INV - Inventarios",
            "PRD - Control de Producción",
            "RGV - Rendicion de Gastos",
            "SEG - Seguridad",
            "TES - Tesoreria",
            "UTL - Utilidades".
. 
