    DEFINE VARIABLE stchq_encarte   AS CHARACTER INITIAL "00".
    DEFINE VARIABLE stchq_deposit   AS CHARACTER INITIAL "01".
    DEFINE VARIABLE stchq_acredit   AS CHARACTER INITIAL "02".
    DEFINE VARIABLE stchq_rechaza   AS CHARACTER INITIAL "03".
    DEFINE VARIABLE stchq_levanta   AS CHARACTER INITIAL "04".
    DEFINE VARIABLE stchq_usuario   AS CHARACTER INITIAL "UU".
    DEFINE VARIABLE stchq_cedido    AS CHARACTER INITIAL "10".
