ON SHIFT-F10 ANYWHERE
DO:
  DISPLAY SELF:TABLE FORMAT "X(32)" LABEL "Tabla" COLON 10 SKIP
          SELF:NAME FORMAT "X(32)"  LABEL "Campo" COLON 10
          WITH FRAME F-D VIEW-AS DIALOG-BOX TITLE "Identifiacion de Campos" SIDE-LABELS.
  PAUSE.
  HIDE FRAME F-D NO-PAUSE.
END.