DEF VAR QQ AS INT INITIAL 175885.

FOR EACH  CAJ_HEADER WHERE NRO_COMPROB = qq:
    FOR EACH CAJ_DETALLE OF CAJ_HEADER:
        DELETE CAJ_DETALLE.
    END.
    DELETE CAJ_HEADER.
    
END.

FOR EACH  rec_HEADER WHERE NRO_COMPROB = qq:
    FOR EACH rec_DETALLE OF rec_HEADER:
        DELETE rec_DETALLE.
    END.
    DELETE rec_HEADER.
    
END.
FOR EACH cta_cte WHERE nro_comprob = qq:
    DELETE cta_cte.
END.

FOR EACH VALOR WHERE IMPORTE = 2449.80:
    DELETE VALOR.
END.
