/* ----------------------- Control del entorno ---------------------------------*/

DEFINE VARIABLE sonido        AS LOGICAL.
DEFINE VARIABLE war_asgprt    AS LOGICAL.
DEFINE VARIABLE dire_tmp      AS CHARACTER.
DEFINE VARIABLE lista_admin   AS CHARACTER INITIAL "ADMIN".
DEFINE VARIABLE SUBSISTEMA    AS CHARACTER.
DEFINE VARIABLE exit_mens     AS INTEGER.
DEFINE VARIABLE VERSION_SIC   AS CHARACTER.
DEFINE VARIABLE LISTA_MODULOS AS CHARACTER INITIAL 
                  "ABA,ADP,BAS,COM,CPS,CXC,CXP,DSP,EXP,FAC,GLA,IMP,INV,OXC,OXP,SEG,TES,UTL,VND".
DEFINE VARIABLE entidad_logon AS INTEGER.

/* --------- Uso general en todos los programas, pero locales a ellos ----------- */

DEFINE VARIABLE aux_ROWID       AS ROWID.
DEFINE VARIABLE ant_ROWID       AS ROWID NO-UNDO.

DEFINE VARIABLE sino_salir      AS LOGICAL.
DEFINE VARIABLE sino_cancel     AS LOGICAL.
DEFINE VARIABLE sino_grabar     AS LOGICAL.
DEFINE VARIABLE hay_error       AS LOGICAL.
DEFINE VARIABLE hubo_error      AS LOGICAL.
DEFINE VARIABLE sino            AS LOGICAL.
DEFINE VARIABLE como_fue        AS LOGICAL.
DEFINE VARIABLE no_aplicar      AS LOGICAL. /* Flag para NO-APPLY DEFL.RESP. en triggers */

DEFINE VARIABLE nom_funcion     AS CHARACTER.
DEFINE VARIABLE nom_menu        AS CHARACTER.
DEFINE VARIABLE titulo_w        AS CHARACTER.

DEFINE VARIABLE stchq_encarte   AS CHARACTER INITIAL "00".
DEFINE VARIABLE stchq_deposit   AS CHARACTER INITIAL "01".
DEFINE VARIABLE stchq_acredit   AS CHARACTER INITIAL "02".
DEFINE VARIABLE stchq_rechaza   AS CHARACTER INITIAL "03".
DEFINE VARIABLE stchq_levanta   AS CHARACTER INITIAL "04".
DEFINE VARIABLE stchq_usuario   AS CHARACTER INITIAL "UU".

DEFINE VARIABLE str_debitan     AS CHARACTER INITIAL "FA,FB,FC,DA,DB,DC,FE,DE,SI,DI".
DEFINE VARIABLE str_debitan_prv AS CHARACTER INITIAL "FA,FB,DA,DB,SI,DI,FC,DC,FE,DE,FX,DX,GP".
DEFINE VARIABLE str_debitan_bco AS CHARACTER INITIAL "CH,DB,EX".
DEFINE VARIABLE str_debitan_inv AS CHARACTER INITIAL "TS,VS,DS,AN,RM,DP".

DEFINE VARIABLE modo_mant       AS INTEGER.
DEFINE VARIABLE dumy_intg       AS INTEGER.
DEFINE VARIABLE dumy_char       AS CHARACTER.
DEFINE VARIABLE dumy_logl       AS LOGICAL.

DEFINE VARIABLE port            AS CHARACTER INITIAL "LPT1".
