  FIELD actividad_dgi LIKE Empleado.actividad_dgi VALIDATE ~
  FIELD calle LIKE Empleado.calle VALIDATE ~
  FIELD carac_servicios LIKE Empleado.carac_servicios VALIDATE ~
  FIELD cdg_afjp LIKE Empleado.cdg_afjp VALIDATE ~
  FIELD cdg_aseguradora LIKE Empleado.cdg_aseguradora VALIDATE ~
  FIELD cdg_banco LIKE Empleado.cdg_banco VALIDATE ~
  FIELD cdg_categoria LIKE Empleado.cdg_categoria VALIDATE ~
  FIELD cdg_convenio LIKE Empleado.cdg_convenio VALIDATE ~
  FIELD cdg_empresa LIKE Empleado.cdg_empresa VALIDATE ~
  FIELD cdg_especializacion LIKE Empleado.cdg_especializacion VALIDATE ~
  FIELD cdg_estado LIKE Empleado.cdg_estado VALIDATE ~
  FIELD cdg_est_civil LIKE Empleado.cdg_est_civil VALIDATE ~
  FIELD cdg_forma LIKE Empleado.cdg_forma VALIDATE ~
  FIELD cdg_franco LIKE Empleado.cdg_franco VALIDATE ~
  FIELD cdg_postal LIKE Empleado.cdg_postal VALIDATE ~
  FIELD cdg_prepaga LIKE Empleado.cdg_prepaga VALIDATE ~
  FIELD cdg_provincia LIKE Empleado.cdg_provincia VALIDATE ~
  FIELD cdg_seccion LIKE Empleado.cdg_seccion VALIDATE ~
  FIELD cdg_sexo LIKE Empleado.cdg_sexo VALIDATE ~
  FIELD cuenta_nro LIKE Empleado.cuenta_nro VALIDATE ~
  FIELD depto LIKE Empleado.depto VALIDATE ~
  FIELD estado_pendiente LIKE Empleado.estado_pendiente VALIDATE ~
  FIELD expedido_por LIKE Empleado.expedido_por VALIDATE ~
  FIELD fecha_baja LIKE Empleado.fecha_baja VALIDATE ~
  FIELD fecha_desde-afjp LIKE Empleado.fecha_desde-afjp VALIDATE ~
  FIELD fecha_ingreso LIKE Empleado.fecha_ingreso VALIDATE ~
  FIELD fecha_nac LIKE Empleado.fecha_nac VALIDATE ~
  FIELD grupo_sanguineo LIKE Empleado.grupo_sanguineo VALIDATE ~
  FIELD id_plan-os LIKE Empleado.id_plan-os VALIDATE ~
  FIELD jubilacion LIKE Empleado.jubilacion VALIDATE ~
  FIELD localidad LIKE Empleado.localidad VALIDATE ~
  FIELD lugar_nac LIKE Empleado.lugar_nac VALIDATE ~
  FIELD nacionalid LIKE Empleado.nacionalid VALIDATE ~
  FIELD nombre LIKE Empleado.nombre VALIDATE ~
  FIELD nom_madre LIKE Empleado.nom_madre VALIDATE ~
  FIELD nom_padre LIKE Empleado.nom_padre VALIDATE ~
  FIELD noretener LIKE Empleado.noretener VALIDATE ~
  FIELD nro_cuil LIKE Empleado.nro_cuil VALIDATE ~
  FIELD nro_empleado LIKE Empleado.nro_empleado VALIDATE ~
  FIELD nro_entidad LIKE Empleado.nro_entidad VALIDATE ~
  FIELD nro_legajo LIKE Empleado.nro_legajo VALIDATE ~
  FIELD numero LIKE Empleado.numero VALIDATE ~
  FIELD numero_doc LIKE Empleado.numero_doc VALIDATE ~
  FIELD obra_social LIKE Empleado.obra_social VALIDATE ~
  FIELD observacion LIKE Empleado.observacion VALIDATE ~
  FIELD piso LIKE Empleado.piso VALIDATE ~
  FIELD rebaja LIKE Empleado.rebaja VALIDATE ~
  FIELD sindicato LIKE Empleado.sindicato VALIDATE ~
  FIELD telefono LIKE Empleado.telefono VALIDATE ~
  FIELD tipo_doc LIKE Empleado.tipo_doc VALIDATE ~
  FIELD total_U78 LIKE Empleado.total_U78 VALIDATE ~
  FIELD ult_familiar LIKE Empleado.ult_familiar VALIDATE ~
  FIELD ult_liquidacion LIKE Empleado.ult_liquidacion VALIDATE ~
  FIELD zona LIKE Empleado.zona VALIDATE 
