/*
databases= "sic"
config= query
version= 2.1A
results.status-area= true 
results.toolbar= true 
results.summary= false
results.governor= 0
results.govergen= false
results.detail-level= 0
results.name= "Totales por Tipo de Proveedor"
results.view-as= report
results.table[1]= "sic.Tipo_proveedor" "936843695" "" "" no ""
results.table[2]= "sic.Proveedor" "1022371114" "OF sic.Tipo_proveedor" "" no ""
results.table[3]= "sic.Cta_cte_prv" "1015068746" "OF sic.Proveedor" "sic.Cta_cte_prv.credito <> sic.Cta_cte_prv.debito" no ""
results.field[1]= "sic.Tipo_proveedor.cdg_tiprove" "Código!Tipo" "X(2)" "&" "character" "" "1" ",,1,1,,"
results.field[2]= "sic.Tipo_proveedor.dsc_tiprove" "Descripción!Tipo" "X(25)" "&" "character" "" "1" ",,25.14,1,,"
results.field[3]= "sic.Proveedor.cdg_proveedor" "Código!Proveedor" "X(8)" "&" "character" "" "1" ",,89.29,1,,"
results.field[4]= "sic.Proveedor.nombre" "Razón!Social" "X(40)" "&" "character" "" "1" ",,1,2.23,,"
results.field[5]= "sic.Cta_cte_prv.tip_comprob" "Tip!Cm." "X(3)" "" "character" "" "1" ",,80.86,2.23,,"
results.field[6]= "sic.Cta_cte_prv.prf_comprob" "Pto.!Vta." "9999" "" "integer" "" "1" ",,100.72,2.23,,"
results.field[7]= "sic.Cta_cte_prv.nro_comprob" "Número!Compbte." "ZZZZZZZ9" "" "integer" "" "1" ",,1,3.46,,"
results.field[8]= "sic.Cta_cte_prv.fecha_vencimiento" "Fecha!Vencmto." "99/99/99" "" "date" "" "1" ",,39.43,3.46,,"
results.field[9]= "sic.Cta_cte_prv.ano" "Año!Imputa" "9999" "" "integer" "" "1" ",,76.43,3.46,,"
results.field[10]= "sic.Cta_cte_prv.mes" "Mes!Imputa" "99" "" "integer" "" "1" ",,102,3.46,,"
results.field[11]= "sic.Cta_cte_prv.credito" "Importe!Crédito" "->,>>>,>>9.99" "t0" "decimal" "" "1" ",,1,4.69,,"
results.field[12]= "sic.Cta_cte_prv.debito" "Importe!Débito" "->,>>>,>>9.99" "t0" "decimal" "" "1" ",,46.57,4.69,,"
results.order[1]= "sic.Tipo_proveedor.cdg_tiprove" "ascending"
results.order[2]= "sic.Proveedor.cdg_proveedor" "ascending"
results.order[3]= "sic.Cta_cte_prv.ano" "ascending"
results.order[4]= "sic.Cta_cte_prv.mes" "ascending"
export.type= PROGRESS
export.use-headings= no 
export.fixed-width= no 
export.prepass= no 
export.base-date= ?
export.record-start= ""
export.record-end= "32,13,10"
export.field-delimiter= "34"
export.field-separator= "32"
export.delimit-type= "*"
export.description= "PROGRESS Export"
form.prop[1]= "sic.Tipo_proveedor,sic.Proveedor,sic.Cta_cte_prv" 0 "" 146,29
label.type= "Default layout"
label.dimension= "3-1/2""x15/16"""
label.left-margin= 0
label.label-width= 35
label.total-height= 5
label.vert-space= 1
label.horz-space= 0
label.number-across= 1
label.number-copies= 1
label.omit-blank= true 
report.format= "Letter"
report.dimension= "8-1/2 x 11 in"
report.time= 0:02
report.left-margin= 1
report.page-size= 60
report.page-width= 158
report.column-spacing= 1
report.line-spacing= 1
report.top-margin= 1
report.before-body= 1
report.after-body= 1
report.page-eject= ""
report.top-left[1]= "Computel S.A."
report.top-left[2]= "{TODAY}"
report.top-center[1]= "Movimientos de Cuenta Corriente por tipo de Proveedor"
report.top-right[1]= "Página {PAGE}"
report.top-right[2]= "{TIME}"
*/

